version: 0.2
phases:
  pre_build:
    commands:
      - pip3 install -r requirements.txt
      - ls
  build:
    commands:
      - ls -ltr
      - cd todo_project/
      - pylint *.py
      - pytest
      - echo Building the application
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -ltr
artifacts:
  files:
    - '**/*'
    - pwd
    - cd /home/ubuntu/devops-app/todo_project
    - pylint *.py
    - cd /home/ubuntu/devops-app/todo_app
    - pylint *.py
    - echo Prebuild ops
