version: 0.2

# environment_variables:
  # plaintext:
  #   DJANGO_SETTINGS_MODULE: config.settings.test
  #   SECRET_KEY: nosecret
  #   DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3
  #   DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
  #   STREAM_INCOMING_PRIVATE_KEY: changeme
  #   STREAM_INCOMING_PUBLIC_KEY: changeme
  #   GOOGLE_API_KEY: changeme
    # OPBEAT_ENABLED: False
# 
phases:
  pre_build:
    commands:
      - pip3 install -r requirements.txt
      - ls
  build:
    commands:
      # - ls -ltr
      # - cd todo_project/
      # - pylint *.py
      # - pytest
      - echo Building the application
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -ltr
artifacts:
  files:
    - '**/*'
    - pwd
    - cd /home/ubuntu/devops-app/todo_project
    - pylint *.py
    - cd /home/ubuntu/devops-app/todo_app
    - pylint *.py
    - echo Prebuild ops
