# Generated by Django 4.2.5 on 2023-12-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todolist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
