# Generated by Django 4.2.5 on 2023-12-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='assignee',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
